import Sidebar from "@/app/(private)/_components/sidebar";
import Navbar from "@/app/(private)/_components/navbar";
export const metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function privateLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-row">
      <Sidebar />
      <div className="w-full h-full">
        <Navbar />
        <div className="w-full h-full p-4">{children}</div>
      </div>
    </div>
  );
}
